version: '3.8'

services:
  mysql:
    image: mysql:8
    restart: always
    environment:
      MYSQL_DATABASE: complaintrestapi
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3307:3307"
    volumes:
      - mysql-data:/var/lib/mysql

  app:
    build: .
    depends_on:
      - mysql
    environment:
      MYSQL_HOST: mysql
    ports:
      - "8081:8081"
    command: ["java", "-jar", "/app.jar"]
    # Optional if using wait-for-it or healthchecks
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  mysql-data:
